# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GCSoundboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GCSoundboard

  target 'GCSoundboardTests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Google-Mobile-Ads-SDK'
  pod 'lottie-ios'


end
